<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Index.aspx.cs" Inherits="MasterNavigation.Index" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <br />
        <br />
        <asp:EntityDataSource ID="EntityDataSource1" runat="server" ConnectionString="name=EarthEntities" DefaultContainerName="EarthEntities" EnableFlattening="False" EntitySetName="Continents" Select="it.[Id], it.[Name]">
        </asp:EntityDataSource>
        <asp:ListBox ID="ContinentsListBox" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ContinentsListBox_SelectedIndexChanged"
            DataSourceID="EntityDataSource1" DataTextField="Name" DataValueField="Id"></asp:ListBox>
        <br />
        <asp:TextBox ID="NewContinent" runat="server"></asp:TextBox>
        <asp:Button ID="AddContinent" runat="server" OnClick="AddContinent_Click" Text="Add" />
        <asp:Button ID="EditContinent" runat="server" OnClick="Button2_Click" Text="Edit" />
        <asp:Button ID="DeleteContinent" runat="server" OnClick="DeleteContinent_Click" Text="Delete" />
        <br />
        <asp:TextBox Id="EditContinentName" runat="server" Visible="false">

        </asp:TextBox>
        <asp:Button ID="SaveContinent" runat="server" Visible="false" OnClick="SaveContinent_Click" Text="Save" />
        <asp:Button ID="CancelContinent" runat="server" Visible="false" OnClick="CancelContinent_Click" Text="Cancel" />
        
        <br />
        <asp:EntityDataSource EnableUpdate="true" EnableInsert="true" EnableDelete="true"
             ID="EntityDataSource4" Where="it.continentId=@contId" runat="server"
             ConnectionString="name=EarthEntities" DefaultContainerName="EarthEntities"
             EnableFlattening="False" EntitySetName="Countries">
            <WhereParameters>
                <asp:ControlParameter Name="contId" Type="Int32" ControlID="ContinentsListBox" />
            </WhereParameters>
        </asp:EntityDataSource>
        <br />
        <asp:GridView AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" ID="GridView1" AllowCustomPaging="True" PageSize="2"
            onpageindexchanging="GridViewCustomers_PageIndexChanging" runat="server"
             AutoGenerateColumns="False" DataKeyNames="Id" DataSourceID="EntityDataSource4"
             AllowPaging="True" AllowSorting="True">
            <Columns>
                <asp:CommandField ShowSelectButton="true" />
                <asp:TemplateField>
                    <HeaderTemplate>
                        <table>
                            <tr>
                                <td></td>
                                <td>Name</td>
                                <td>Language</td>
                                <td>Population</td>
                            </tr>
                    </HeaderTemplate>
                    <ItemTemplate>
                            <tr>
                                <td></td>
                                <td><%#: Eval("Name") %></td>
                                <td><%#: Eval("Language") %></td>
                                <td><%#: Eval("Population") %></td>
                            </tr>
                    </ItemTemplate>
                    <FooterTemplate>
                        </table>
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
        <br />
        <asp:TextBox ID="NewCountryName" runat="server"></asp:TextBox>
        <br />
        <asp:TextBox ID="NewCountryLanguage" runat="server"></asp:TextBox>
        <br />
        <asp:TextBox ID="NewCountryPopulation" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Insert" />
        <br />
        <asp:EntityDataSource ID="EntityDataSource3" EnableDelete="true" EnableInsert="true" EnableUpdate="true" Where="it.countryId=@countryId" runat="server" ConnectionString="name=EarthEntities" DefaultContainerName="EarthEntities" EnableFlattening="False" EntitySetName="Towns">
            <WhereParameters>
                <asp:ControlParameter Name="countryId" Type="Int32" ControlID="GridView1" />
            </WhereParameters>
        </asp:EntityDataSource>
        <asp:ListView ID="ListView1" runat="server" DataKeyNames="Id" DataSourceID="EntityDataSource3">
            <AlternatingItemTemplate>
                <tr style="">
                    <td>
                        <asp:Label ID="IdLabel" runat="server" Text='<%# Eval("Id") %>' />
                    </td>
                    <td>
                        <asp:Label ID="NameLabel" runat="server" Text='<%# Eval("Name") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryIdLabel" runat="server" Text='<%# Eval("CountryId") %>' />
                    </td>
                    <td>
                        <asp:Label ID="PopulationLabel" runat="server" Text='<%# Eval("Population") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryLabel" runat="server" Text='<%# Eval("Country") %>' />
                    </td>
                </tr>
            </AlternatingItemTemplate>
            <EditItemTemplate>
                <tr style="">
                    <td>
                        <asp:Label ID="IdLabel" runat="server" Text='<%# Eval("Id") %>' />
                    </td>
                    <td>
                        <asp:Label ID="NameLabel" runat="server" Text='<%# Eval("Name") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryIdLabel" runat="server" Text='<%# Eval("CountryId") %>' />
                    </td>
                    <td>
                        <asp:Label ID="PopulationLabel" runat="server" Text='<%# Eval("Population") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryLabel" runat="server" Text='<%# Eval("Country") %>' />
                    </td>
                </tr>
            </EditItemTemplate>
            <EditItemTemplate>
                <tr style="">
                    <td>
                        <asp:Button ID="UpdateButton" runat="server" CommandName="Update" Text="Update" />
                        <asp:Button ID="CancelButton" runat="server" CommandName="Cancel" Text="Cancel" />
                    </td>
                    <td>
                        <asp:Label ID="IdLabel1" runat="server" Text='<%# Eval("Id") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="NameTextBox" runat="server" Text='<%# Bind("Name") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="CountryIdTextBox" runat="server" Text='<%# Bind("CountryId") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="PopulationTextBox" runat="server" Text='<%# Bind("Population") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="CountryTextBox" runat="server" Text='<%# Bind("Country") %>' />
                    </td>
                </tr>
            </EditItemTemplate>
            <EmptyDataTemplate>
                <table runat="server" style="">
                    <tr>
                        <td>No data was returned.</td>
                    </tr>
                </table>
            </EmptyDataTemplate>
            <InsertItemTemplate>
                <tr style="">
                    <td>
                        <asp:Button ID="InsertButton" runat="server" CommandName="Insert" Text="Insert" />
                        <asp:Button ID="CancelButton" runat="server" CommandName="Cancel" Text="Clear" />
                    </td>
                    <td>
                        <asp:TextBox ID="IdTextBox" runat="server" Text='<%# Bind("Id") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="NameTextBox" runat="server" Text='<%# Bind("Name") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="CountryIdTextBox" runat="server" Text='<%# Bind("CountryId") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="PopulationTextBox" runat="server" Text='<%# Bind("Population") %>' />
                    </td>
                    <td>
                        <asp:TextBox ID="CountryTextBox" runat="server" Text='<%# Bind("Country") %>' />
                    </td>
                </tr>
            </InsertItemTemplate>
            <ItemTemplate>
                <tr style="">
                    <td>
                        <asp:Label ID="IdLabel" runat="server" Text='<%# Eval("Id") %>' />
                    </td>
                    <td>
                        <asp:Label ID="NameLabel" runat="server" Text='<%# Eval("Name") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryIdLabel" runat="server" Text='<%# Eval("CountryId") %>' />
                    </td>
                    <td>
                        <asp:Label ID="PopulationLabel" runat="server" Text='<%# Eval("Population") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryLabel" runat="server" Text='<%# Eval("Country") %>' />
                    </td>
                </tr>
            </ItemTemplate>
            <LayoutTemplate>
                <table runat="server">
                    <tr runat="server">
                        <td runat="server">
                            <table id="itemPlaceholderContainer" runat="server" border="0" style="">
                                <tr runat="server" style="">
                                    <th runat="server">Id</th>
                                    <th runat="server">Name</th>
                                    <th runat="server">CountryId</th>
                                    <th runat="server">Population</th>
                                    <th runat="server">Country</th>
                                </tr>
                                <tr id="itemPlaceholder" runat="server">
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr runat="server">
                        <td runat="server" style="">
                        </td>
                    </tr>
                </table>
            </LayoutTemplate>
            <SelectedItemTemplate>
                <tr style="">
                    <td>
                        <asp:Label ID="IdLabel" runat="server" Text='<%# Eval("Id") %>' />
                    </td>
                    <td>
                        <asp:Label ID="NameLabel" runat="server" Text='<%# Eval("Name") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryIdLabel" runat="server" Text='<%# Eval("CountryId") %>' />
                    </td>
                    <td>
                        <asp:Label ID="PopulationLabel" runat="server" Text='<%# Eval("Population") %>' />
                    </td>
                    <td>
                        <asp:Label ID="CountryLabel" runat="server" Text='<%# Eval("Country") %>' />
                    </td>
                </tr>
            </SelectedItemTemplate>
        </asp:ListView>
        <asp:DataPager ID="DataPager1" runat="server" PageSize="3" PagedControlID="ListView1">
            <Fields>
                <asp:NextPreviousPagerField ButtonType="Button" ShowFirstPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
                <asp:NumericPagerField />
                <asp:NextPreviousPagerField ButtonType="Button" ShowLastPageButton="True" ShowNextPageButton="False" ShowPreviousPageButton="False" />
            </Fields>
        </asp:DataPager>
        <br />
        <asp:TextBox ID="NewTownName" runat="server"></asp:TextBox>
        <br />
        <asp:TextBox ID="NewTownPopulation" runat="server"></asp:TextBox>
        <br />
        <asp:Button ID="Button2" runat="server" OnClick="Button2_Click1" Text="Insert" />
        <br />
    </div>
    </form>
</body>
</html>
