//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceLibraryClient.ServiceLibraryReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLibraryReference.IServiceLibrary")]
    public interface IServiceLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/GetCountSecondContainsFirst", ReplyAction="http://tempuri.org/IServiceLibrary/GetCountSecondContainsFirstResponse")]
        int GetCountSecondContainsFirst(string first, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLibrary/GetCountSecondContainsFirst", ReplyAction="http://tempuri.org/IServiceLibrary/GetCountSecondContainsFirstResponse")]
        System.Threading.Tasks.Task<int> GetCountSecondContainsFirstAsync(string first, string second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLibraryChannel : WebServiceLibraryClient.ServiceLibraryReference.IServiceLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLibraryClient : System.ServiceModel.ClientBase<WebServiceLibraryClient.ServiceLibraryReference.IServiceLibrary>, WebServiceLibraryClient.ServiceLibraryReference.IServiceLibrary {
        
        public ServiceLibraryClient() {
        }
        
        public ServiceLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCountSecondContainsFirst(string first, string second) {
            return base.Channel.GetCountSecondContainsFirst(first, second);
        }
        
        public System.Threading.Tasks.Task<int> GetCountSecondContainsFirstAsync(string first, string second) {
            return base.Channel.GetCountSecondContainsFirstAsync(first, second);
        }
    }
}
